/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lyndir_masterpassword_MPAlgorithm_Version */

#ifndef _Included_com_lyndir_masterpassword_MPAlgorithm_Version
#define _Included_com_lyndir_masterpassword_MPAlgorithm_Version
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lyndir_masterpassword_MPAlgorithm_Version_AES_BLOCKSIZE
#define com_lyndir_masterpassword_MPAlgorithm_Version_AES_BLOCKSIZE 128L
/*
 * Class:     com_lyndir_masterpassword_MPAlgorithm_Version
 * Method:    _masterKey
 * Signature: (Ljava/lang/String;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lyndir_masterpassword_MPAlgorithm_00024Version__1masterKey
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     com_lyndir_masterpassword_MPAlgorithm_Version
 * Method:    _siteKey
 * Signature: ([BLjava/lang/String;JILjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lyndir_masterpassword_MPAlgorithm_00024Version__1siteKey
  (JNIEnv *, jobject, jbyteArray, jstring, jlong, jint, jstring, jint);

/*
 * Class:     com_lyndir_masterpassword_MPAlgorithm_Version
 * Method:    _siteResult
 * Signature: ([B[BLjava/lang/String;JILjava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lyndir_masterpassword_MPAlgorithm_00024Version__1siteResult
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jlong, jint, jstring, jint, jstring, jint);

/*
 * Class:     com_lyndir_masterpassword_MPAlgorithm_Version
 * Method:    _siteState
 * Signature: ([B[BLjava/lang/String;JILjava/lang/String;ILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lyndir_masterpassword_MPAlgorithm_00024Version__1siteState
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jlong, jint, jstring, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
