workspace 'MasterPassword'
project 'MasterPassword-iOS'

platform :ios, '9.3'

target 'MasterPassword' do
  use_modular_headers!
  use_frameworks!

  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  pod 'Countly'
end
