workspace 'MasterPassword'
project 'MasterPassword-iOS'
project 'MasterPassword-macOS'

target 'MasterPassword-iOS' do
  project 'MasterPassword-iOS'
  platform :ios, '9.3'

  use_modular_headers!
  use_frameworks!

  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  pod 'Countly'
  pod 'UIColor-Utilities'
  pod 'KCOrderedAccessorFix'
  pod 'JRSwizzle'
end

target 'MasterPassword-macOS' do
  project 'MasterPassword-macOS'
  platform :osx, '10.11'

  use_modular_headers!
  use_frameworks!

  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  pod 'Countly'
  pod 'KCOrderedAccessorFix'
  pod 'JRSwizzle'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Countly-iOS' || target.name == 'Countly-macOS'
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'COUNTLY_EXCLUDE_IDFA=1'
      end
    end
  end
end
