workspace 'MasterPassword'
project 'MasterPassword-iOS'
project 'MasterPassword-macOS'

target 'MasterPassword-iOS' do
  project 'MasterPassword-iOS'
  platform :ios, '9.3'

  use_modular_headers!
  use_frameworks!

  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  pod 'Countly'
end

target 'MasterPassword-macOS' do
  project 'MasterPassword-macOS'
  platform :osx, '10.11'

  use_modular_headers!
  use_frameworks!

  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  pod 'Countly'
end
