#!/usr/bin/env bash
set -e

cd "${BASH_SOURCE[0]%/*}"
nice rsync --partial --progress --delete --sparse --archive --no-owner --no-perms --no-group --chmod=ugo=rwX \
    --exclude rate-limit \
    . masterpassword.lyndir.com:/usr/local/www/masterpassword.lyndir.com/htdocs/
