/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lyndir_masterpassword_impl_MPAlgorithmV0 */

#ifndef _Included_com_lyndir_masterpassword_impl_MPAlgorithmV0
#define _Included_com_lyndir_masterpassword_impl_MPAlgorithmV0
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lyndir_masterpassword_impl_MPAlgorithmV0_AES_BLOCKSIZE
#define com_lyndir_masterpassword_impl_MPAlgorithmV0_AES_BLOCKSIZE 128L
/*
 * Class:     com_lyndir_masterpassword_impl_MPAlgorithmV0
 * Method:    _scrypt
 * Signature: ([B[BIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_lyndir_masterpassword_impl_MPAlgorithmV0__1scrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
