#! /usr/bin/env bash
source bashlib
shopt -s nullglob

emit "Converting iTunesArtwork"
icons=(
    [29]="Icon-Small.png"
    [50]="Icon-Small-50.png"
    [58]="Icon-Small@2x.png"
    [57]="Icon.png"
    [72]="Icon-72.png"
    [114]="Icon@2x.png"
)
cd "${0%/*}/../MasterPassword/Resources"

for size in "${!icons[@]}"; do
    file=${icons[size]}

    emit "$file ($size px)" --
        convert "iTunesArtwork.png" -resize "${size}x${size}" "$file"
    emit -$?
done


echo
emit "Converting @2x artwork"
for file in ./{,Guide/}*@2x.png; do
    inArray "${file##*/}" "${icons[@]}" && continue

    emit "${file/@2x}" --
        convert "$file" -filter box -resize 50% -unsharp 0x1 "${file/@2x}"
    emit -$?
done

